apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vf3q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-vf3q@sha256:320eb60b34daa39cba5af77dd9f1a74e827f26a1da6f167aca0fa0df8142c21d
        name: my-nodejs
        resources: {}
status: {}
